# Generated by Django 5.2.3 on 2025-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointmen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_info',
            name='specialist',
            field=models.CharField(choices=[('neurologist', 'Neurologist'), ('dentist', 'Dentist'), ('gyneacologist', 'Gynecologist'), ('cardiologist', 'Cardiologist')], max_length=100),
        ),
    ]
